### ISSUE TITLE
I'm sorry I have a problem

### ISSUE THREAD

**Issue by Liyang131313** [sslab-gatech/hdfi#2]
root@zynq:~# ./fesvr-zynq pk ripe_attack_generator
Error: Unknown choice of buffer location

Excuse me, I want to perform RIPE testing. I have encountered this problem. How can I solve it

Should RIPE have to be tested on a modified structure or can it be run on a generic RISCV architecture?

**Comment by ChengyuSong** [comment]
ripe_attack_generator expects arguments, please check ripe_test.py to see how to invoke it.

**Comment by Liyang131313** [comment]
Excuse me, I still have a problem about the RIPE Benchmark which is modify it to make it work on the RISC-V architecture .How to set the argument of adventure_attack_generator to get the result of the test benchmark, Could I trouble you to display the input command line operations? And Where can the results be viewed, and how can the results be analyzed? Can this RIPE Benchmark test be run only on the evaluation board or can be simulated with spike pk? please help me .....thank you,this problem has troubled me for along time.....I really wat to know how to use this Benchmark.
