### ISSUE TITLE
RIPE Benchmark

### ISSUE THREAD

**Issue by Liyang131313** [sslab-gatech/hdfi#3]
Excuse me, I still have a problem about the RIPE Benchmark which is modify it to make it work on the RISC-V architecture .How to set the argument of adventure_attack_generator to get the result of the test benchmark, Could I trouble you to display the input command line operations? And Where can the results be viewed, and how can the results be analyzed? Can this RIPE Benchmark  test be run only on the evaluation board or can be simulated with spike pk? please help me .....thank you,this problem has troubled me for along time.....I really wat to know how to use this Benchmark.

**Comment by ChengyuSong** [comment]
I have told you to use ripe_tester.py ...

**Comment by Liyang131313** [comment]
@ChengyuSong Sorry, thank you very much. . I would also like to ask if this RIPE Benchmark is only applicable to hdfi? Can I use it on the lowRISC directly?
